app:
  hostname: HOSTNAME
  server:
    protocol: HANCOCK_SERVER_PROTOCOL
    host: HANCOCK_SERVER_HOST
    port: HANCOCK_SERVER_PORT
    externalPort: HANCOCK_SERVER_EXTERNAL_PORT
    base: HANCOCK_SERVER_BASE
    externalBase: HANCOCK_SERVER_EXTERNAL_BASE
  blockchain:
    ethereum:
      protocol: HANCOCK_BLOCKCHAIN_ETHEREUM_PROTOCOL
      host: HANCOCK_BLOCKCHAIN_ETHEREUM_HOST
      port: HANCOCK_BLOCKCHAIN_ETHEREUM_PORT
  db:
    protocol: HANCOCK_DB_PROTOCOL
    hosts: HANCOCK_DB_HOSTS
    database: HANCOCK_DB_DATABASE
    params: HANCOCK_DB_PARAMS
    user: HANCOCK_DB_USER
    pass: HANCOCK_DB_PASS
    ethereum:
      database: HANCOCK_DB_ETHEREUM_DATABASE
  cryptvault:
    api:
      getByAddressEndpoint: HANCOCK_CRYPTVAULT_GET_BY_ADDRESS_ENDPOINT
      signEndpoint: HANCOCK_CRYPTVAULT_SIGN_ENDPOINT
    credentials:
      key: HANCOK_CRYPTVAULT_KEY
      secret: HANCOCK_CRYPTVAULT_SECRET
      expires_in: HANCOCK_CRYPTVAULT_EXPIRES_IN