env: production
app:
  server:
    host: 'https://hancock-wallet-hub-blockchain-demo.kickstartteam.es'
    port: 80
  blockchain:
    ethereum:
      host: kst-hancock-ms-ganache-cli.blockchainhub-develop
  db:
    host: mongo.blockchainhub-develop
    database: hancock
    eth:
      database: hancock
      collections:
        contracts: smartcontracts
        providers: providers